### ISSUE TITLE
Value cannot be null (parameter 'source') when running idl.json created via Devnet

### ISSUE THREAD

**Issue by Rojax98** [bmresearch/Solnet.Anchor#18]
When running the anchorgen command with the json file the following error is thrown: 

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Solnet.Anchor.ClientGenerator.GenerateGetAccounts(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 1524
   at Solnet.Anchor.ClientGenerator.GenerateClientSyntaxTree(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 904
   at Solnet.Anchor.ClientGenerator.GenerateSyntaxTree(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 71
   at Solnet.Anchor.ClientGenerator.GenerateCode(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 84
   at AnchorSourceGenerator.<>c.<Main>b__0_1(CommandLineOptions opts) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor.Tool/AnchorSourceGenerator.cs:line 56
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at AnchorSourceGenerator.Main(String[] args) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor.Tool/AnchorSourceGenerator.cs:line 19

**Comment by Rojax98** [comment]
The idl json that we were using did not have the data for the field:

public IIdlTypeDefinitionTy[] Accounts { get; set; }

We were just creating a quick hello world demo hence the small scale.

**Comment by tiago18c** [comment]
Just fixed it. You should have a new version of the tool available in a few minutes in nuget :)
